
platform :ios, '7.0'
xcodeproj 'Q-municate.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'

pod 'UIDevice-Hardware', '~> 0.1.3'
pod 'SVProgressHUD', '~> 1.0'
pod 'Parus', '~> 1.0'
pod 'StaticDataTableViewController', '~> 2.0.3'
pod 'SSKeychain', '~> 1.2.2'
pod 'AGEmojiKeyboard', '~> 0.1.0'
pod 'SDWebImage', '~> 3.6'
pod 'IDMPhotoBrowser', '~> 1.3.5'
pod 'MPGNotification', '~> 1.1'
pod 'Reachability', '~> 3.2'
pod 'QMServices', :podspec => 'QMServicesDevelopment.podspec'
pod 'QuickBlox'
pod 'TTTAttributedLabel', '~> 1.13'